### ISSUE TITLE
Add option for local copy of goss

### ISSUE THREAD

**Issue by gforster** [naftulikay/ansible-role-degoss#54]
Does not work against boxes that have no route to GitHub (NAT'd, firewall rules, etc.). Would be nice to have an option to pre-download and provide a local copy (on the ansible control machine) of goss for these types of situations. Might be nice anyway to make the single call to GitHub and then copy goss out anyway. At least as an option.

**Comment by naftulikay** [comment]
Thanks for opening an issue.

I'm open for pull requests, but presently I don't have the throughput to add this feature, and in all of the environments which I've had use-cases for this, there is an assumption of internet access. If you'd like to create a PR and add another test case to CI to ensure that we prove this is supported going forward :+1:

**Comment by SamuelMwangiW** [comment]
Hi @naftulikay. 

I discovered this issue posted on [upwork](https://www.upwork.com/ab/proposals/1316266838149500929?success).
Am open to a PR but need confirmation if my understanding of the issue is correct.

My understanding of this issue is that a user can copy the gross binary from the control machine to the remote host.
If this be the case, then am proposing a PR that defines variables which the user overrides in the playbook with the binary location and a boolean which if true runs the tasks to copy the binary. The boolean will be default `false`.

Kindly let me know if my explanation makes sense and we'll review the the PR in a few
